pandas.errors.PossibleDataLossError
===================================

.. currentmodule:: pandas.errors

.. autoexception:: PossibleDataLossError