pandas.errors.ChainedAssignmentError
====================================

.. currentmodule:: pandas.errors

.. autoexception:: ChainedAssignmentError